// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo4NdecrKnUn8C3fHWtDHIBY78sHVPaR8',
    appId: '1:470380588012:web:97e612da063a8dbe08eec9',
    messagingSenderId: '470380588012',
    projectId: 'flutter-list-database-373f2',
    authDomain: 'flutter-list-database-373f2.firebaseapp.com',
    databaseURL: 'https://flutter-list-database-373f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-list-database-373f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLIFa5lN_tJB9vg25HUvrpMrhBQGIkHnY',
    appId: '1:470380588012:android:55587a593edc60e108eec9',
    messagingSenderId: '470380588012',
    projectId: 'flutter-list-database-373f2',
    databaseURL: 'https://flutter-list-database-373f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-list-database-373f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZvkmPikQPOXRvCCS5aCo0xJJ6T8CWc0',
    appId: '1:470380588012:ios:7d6b5f4a65232cf608eec9',
    messagingSenderId: '470380588012',
    projectId: 'flutter-list-database-373f2',
    databaseURL: 'https://flutter-list-database-373f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-list-database-373f2.appspot.com',
    iosClientId: '470380588012-hk11d2av7gpv41blhjktgh7uuc3dpg0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingListApp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZvkmPikQPOXRvCCS5aCo0xJJ6T8CWc0',
    appId: '1:470380588012:ios:776f6c3abad0f88908eec9',
    messagingSenderId: '470380588012',
    projectId: 'flutter-list-database-373f2',
    databaseURL: 'https://flutter-list-database-373f2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-list-database-373f2.appspot.com',
    iosClientId: '470380588012-avtle9vknun2te6r96ph0lo9js9p4b7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingListApp01.RunnerTests',
  );
}
